name: Bug report
description: Report incorrect or unexpected behavior of an example
labels: [bug, need repro]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing an issue! If you are here to ask a question, use Discord instead: https://discord.gg/djs

        This issue form is for @discordjs/voice examples
  - type: dropdown
    id: package
    attributes:
      label: Which example is this bug report for?
      options:
        - basic
        - radio-bot
        - recorder
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce with below code sample:
        1. Do thing
        2. Do thing in Discord client
        3. Observe behavior
        4. See error logs below
    validations:
      required: true
  - type: textarea
    id: code_sample
    attributes:
      label: Code sample
      description: |
        Your code sample should be:
        1. Minimal - Use as little code as possible that still produces the same problem (and is understandable)
        2. Complete - Provide all parts someone else needs to reproduce your problem
        3. Reproducible - Test the code you're about to provide to make sure it reproduces the problem

        This will be automatically formatted into code, so no need for backticks.
      render: typescript
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: List necessary versions here. This includes your @discordjs/voice version, runtime version, operating system etc.
      placeholder: |
        - @discordjs/voice 0.17.0 (`npm ls @discordjs/voice`)
        - Node.js 20.15.0 (`node --version`)
        - TypeScript 5.4.5 (`npm ls typescript` if you use it)
        - macOS Ventura 13.3.1
    validations:
      required: true
  - type: input
    id: dev-release
    attributes:
      label: I have tested this issue on a development release
      placeholder: d23280c (commit hash)
      description: |
        The issue might already be fixed in a development release or main. This is not required, but helps us greatly.
        To install the latest development release run `npm i @discordjs/voice@dev` in your project directory.
        Run `npm list @discordjs/voice` and use the last part of the printed information (`d23280c` for `@discordjs/voice@xx.x.x-dev.1530234593-d23280c`)
